// <auto-generated />
using System;
using EFWork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFWork.Migrations
{
    [DbContext(typeof(macdonaldsWorkContext))]
    partial class macdonaldsWorkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.3.22175.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFWork.Models.Document", b =>
                {
                    b.Property<int>("DocumentsPackId")
                        .HasColumnType("int");

                    b.Property<int?>("ControlListId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploementHistory")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalBook")
                        .HasColumnType("int");

                    b.Property<int?>("PasportId")
                        .HasColumnType("int");

                    b.Property<int?>("Snils")
                        .HasColumnType("int")
                        .HasColumnName("SNILS");

                    b.HasKey("DocumentsPackId")
                        .HasName("PK__Document__2104C85E41EBEFF1");

                    b.HasIndex(new[] { "PasportId" }, "UQ__Document__07E30CA0F29E4E30")
                        .IsUnique()
                        .HasFilter("[PasportId] IS NOT NULL");

                    b.HasIndex(new[] { "MedicalBook" }, "UQ__Document__2D66F6430DB004A5")
                        .IsUnique()
                        .HasFilter("[MedicalBook] IS NOT NULL");

                    b.HasIndex(new[] { "ControlListId" }, "UQ__Document__4CE954544317CD4D")
                        .IsUnique()
                        .HasFilter("[ControlListId] IS NOT NULL");

                    b.HasIndex(new[] { "Snils" }, "UQ__Document__7EB2A6F9C32908ED")
                        .IsUnique()
                        .HasFilter("[SNILS] IS NOT NULL");

                    b.HasIndex(new[] { "EmploementHistory" }, "UQ__Document__A81A8E1A90305683")
                        .IsUnique()
                        .HasFilter("[EmploementHistory] IS NOT NULL");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EFWork.Models.Employee", b =>
                {
                    b.Property<int>("TableNumberId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfPromotion")
                        .HasColumnType("date");

                    b.Property<int?>("DocumentsPackId")
                        .HasColumnType("int");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("SizeOfClothes")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TableNumberId")
                        .HasName("PK__Employee__EB6F9EC90E204A3B");

                    b.HasIndex("DocumentsPackId");

                    b.HasIndex("PostId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("EFWork.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "JobTitle" }, "UQ__Posts__44C68B9F5CAFB844")
                        .IsUnique()
                        .HasFilter("[JobTitle] IS NOT NULL");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFWork.Models.Employee", b =>
                {
                    b.HasOne("EFWork.Models.Document", "DocumentsPack")
                        .WithMany("Employees")
                        .HasForeignKey("DocumentsPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Employee__Docume__403A8C7D");

                    b.HasOne("EFWork.Models.Post", "Post")
                        .WithMany("Employees")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK__Employee__PostId__412EB0B6");

                    b.Navigation("DocumentsPack");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EFWork.Models.Document", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EFWork.Models.Post", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
